package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setGrage(java.lang.String grage) {
		set("grage", grage);
	}

	public java.lang.String getGrage() {
		return get("grage");
	}

	public void setClasses(java.lang.String classes) {
		set("classes", classes);
	}

	public java.lang.String getClasses() {
		return get("classes");
	}

}
